### ISSUE TITLE
How to set bbgain?

### ISSUE THREAD

**Issue by dobcrypto** [zcpnate/Gunbot-Polo-Updater#1]
Hi, man.
How to set bbgain?
Or its only for bbstepgain?

**Comment by zcpnate** [comment]
Set your strategy bbgain in your main config file to the settings you want. Then set the strategy variable for medium and/or high to bbgain

**Comment by dobcrypto** [comment]
But so bot will trade in the overall bbgain strategy settings.
Will the settings not interfere with SELLLVL1/2/3 in nate-updateGB?

**Comment by zcpnate** [comment]
correct, those settings will only apply if your strategy variable includes a stepgain setting

**Comment by zcpnate** [comment]
Also, recommended PHP 7.0.22+
